name: Foundry CI

on:
  push:
    branches: [dev, master, main]
  pull_request:
    branches: [dev, master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Setup NodeJS 20.5.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0

      - name: Show NodeJS version
        run: npm --version

      - name: Install Project Dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --ffi -vvv
        id: test